"Detection":
  - changed-files:
    - any-glob-to-any-file: 
      - 'detection/**/*'

"Network":
  - changed-files:
    - any-glob-to-any-file: 
      - 'network/**/*'

"Motion":
  - changed-files:
    - any-glob-to-any-file: 
      - 'motion/**/*'

"Logic":
  - changed-files:
    - any-glob-to-any-file: 
      - 'controller/**/*'

"Storage":
  - changed-files:
    - any-glob-to-any-file:
      - 'storage/**/*'

"Documentation":
  - changed-files:
    - any-glob-to-any-file: 
      - 'README.md'
      - 'docs/**/*'

"Tests":
  - changed-files:
    - any-glob-to-any-file: 
      - 'test/**/*'

"CI/CD":
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'
      - 'platformio.ini' # הוספתי את קובץ ההגדרות הראשי של הפרויקט

"Music/SFX":
  - changed-files:
    - any-glob-to-any-file:
      - 'music/**/*'
